databases:
  - name: product-importer-db
    plan: free
    databaseName: products_db

services:
  - type: redis
    name: product-importer-redis
    plan: free
    ipAllowList: []

  - type: web
    name: product-importer-api
    plan: free
    env: python
    buildCommand: "./build.sh"
    startCommand: "celery -A celery_app worker --loglevel=info --concurrency=1 & uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: product-importer-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: product-importer-redis
          type: redis
          property: connectionString
      - key: FRONTEND_URL
        value: https://product-importer-frontend.onrender.com

  - type: web
    name: product-importer-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: product-importer-api
          envVarKey: RENDER_EXTERNAL_URL
